Export new metrics and add status label
tobbez/deluge_exporter pull request #17
Opened 2022-01-23 18:19 UTC by ibizaman

This PR does two things. I can split them if you want.

First, it adds a state label to torrent specific metrics. I wanted to only show torrents that are in downloading state on some graphs and adding the label ok the metrics was the easiest. I tried first using a query join transformation in grafana and other transforms but couldn’t figure it out.

Second, it adds a few metrics coming from deluge like the added one that was requested in another issue.

2022-01-24 23:01 UTC, tobbez requested changes
Using the same PR is acceptable (assuming unrelated changes are separated into different commits), but splitting it up would have been better.

The changes looks fine apart from the comments inline.

While you're rewriting the commit history, please also update the message of the "add more metrics" commit to "add more per-torrent metrics".

It's a bit unfortunate that Deluge inconsistently renames some of the libtorrent metrics (e.g. libtorrent's `all_time_upload` is renamed to `total_uploaded` while `all_time_download` preserves the libtorrent name). We'll just have to live with that for now (the fix would be to add functionality to Deluge to return the raw per-torrent libtorrent metrics).

Some of the metrics added are deprecated in libtorrent 1.2 and removed in 2.0 (`time_since_upload`, `time_since_download`, `active_time`, `finished_time`, `seeding_time`), but I suppose we can keep them until Deluge migrates to libtorrent 2.0.

2022-01-24 23:01 UTC, tobbez commented on deluge_exporter.py
> +        torrents_with_state = defaultdict(int)
Rename to torrent_states and change type to regular dict (defaultdict is not needed here). That makes it:

```python
torrent_states = {}
```

2022-01-24 23:01 UTC, tobbez commented on deluge_exporter.py
> +        for torrent in client.core.get_torrents_status({}, [b"name", b"label", b"state", b"download_payload_rate", b"upload_payload_rate"]).values():
The states dict should be keyed by info hash, since names are not guaranteed to be unique, meaning this becomes:

```py
for torrent_hash, torrent in client.core.get_torrents_status({}, [b"label", b"state", b"download_payload_rate", b"upload_payload_rate"]).items():
```

2022-01-24 23:01 UTC, tobbez commented on deluge_exporter.py
> +            torrents_with_state[torrent[b"name"]] = torrent[b"state"].decode("utf-8").lower()
```py
torrent_states[torrent_hash] = torrent[b"state"].decode("utf-8").lower()
```

(as previously: rename the dict and use the hash as the key)

2022-01-24 23:01 UTC, tobbez commented on deluge_exporter.py
> +                (GaugeMetricFamily, b"finished_time", "When this torrent finished being active"),
Incorrect. This is `The number of seconds this torrent has spent in the finished state`.

2022-01-24 23:01 UTC, tobbez commented on deluge_exporter.py
> +                (GaugeMetricFamily, b"all_time_download", "The amount of time downloading the torrent"),
Incorrect. This is the total number of payload bytes downloaded across all sessions.

2022-01-24 23:01 UTC, tobbez commented on deluge_exporter.py
> +                (GaugeMetricFamily, b"last_seen_complete", "When was the last time we saw the complete torrent on the swarm"),
Better expressed as "The time when we last saw a seed or peers that together formed a complete copy of the torrent".

2022-01-24 23:01 UTC, tobbez commented on deluge_exporter.py
> +                (GaugeMetricFamily, b"progress", "Torrent progress percentage"),
I'm not convinced this should be included. It's a derived metric that can be calculated using `total_done/total_size`.

2022-01-24 23:01 UTC, tobbez commented on deluge_exporter.py
> +                (GaugeMetricFamily, b"seeds_peers_ratio", "Torrent ratio"),
Incorrect. This is the ratio between the number of seeds and number of peers, which should already be possible to calculate (using num_peers and num_seeds). It can thus be removed.

The actual torrent ratio can also be calculated using other metrics (`total_uploaded/all_time_download`).

2022-01-24 23:01 UTC, tobbez commented on deluge_exporter.py
> +                    metric.add_metric([torrent[b"name"].decode("utf-8"), torrent_hash.decode("utf-8"), torrents_with_state[torrent[b"name"]]], torrent[metric_name])
```python
metric.add_metric([torrent[b"name"].decode("utf-8"), torrent_hash.decode("utf-8"), torrent_states[torrent_hash]], torrent[metric_name])
```

(as previously: rename the dict and use the hash as the key)

2022-01-26 06:36 UTC, ibizaman commented
Thank you for the thorough review! I implemented all your comments. I also added the metrics to the Readme as well as adding `state=` as label and also fixed the naming of the `deluge_torrent_total_*` metrics.

2022-01-26 17:51 UTC, tobbez requested changes
Two issues that need to be fixed (the current version won't work at all when per-torrent metrics are enabled).

You can also skip updating the metrics table if you like. I need to regenerate it after this PR is merged anyway.

2022-01-26 17:51 UTC, tobbez commented on deluge_exporter.py
> +                (GaugeMetricFamily, b"active_time", "The number of seconds this torrent has been active. i.e. not paused")
Missing trailing comma.

2022-01-26 17:51 UTC, tobbez commented on deluge_exporter.py
> +        for torrent_hash, torrent in client.core.get_torrents_status({}, [b"label", b"state", b"download_payload_rate", b"upload_payload_rate"]).values():
This needs to be `.items()`, not `.values()`.

2022-02-11 04:34 UTC, ibizaman commented
Sorry for the wait.

2022-04-13 23:17 UTC, tobbez approved these changes

2022-04-13 23:19 UTC, merged